### ISSUE TITLE
Redefinition is buggy

### ISSUE THREAD

**Issue by tekknolagi** [Jumhyn/JumLang#3]
```
[int fac: int num] {
    int res = 1;
    while (num > 0) {
        res = res * num;
        num = num - 1;
    }
    return res;
}

[int main] {
    int x = [fac: 6];
    return x;
}
```

Generates

```
target triple = "x86_64-apple-macosx10.9.0"
define i32 @fac(i32 %num) {
%res = alloca i32
store i32 1, i32* %res
br label %L3
L3:
%t1 = icmp sgt i32 %num, 0
br i1 %t1, label %L5, label %L4
L5:
%t2 = load i32* %res
%t3 = mul i32 %t2, %num
store i32 %t3, i32* %res
%num = alloca i32
%t4 = sub i32 %num, 1
store i32 %t4, i32* %num
br label %L3
L4:
%t5 = load i32* %res
ret i32 %t5
}
define i32 @main() {
%x = alloca i32
%t6 = call i32 @fac(i32 6)
store i32 %t6, i32* %x
%t7 = load i32* %x
ret i32 %t7
}
```

Which throws:
![screen shot 2014-07-10 at 12 00 23 am](https://butt.githubusercontent.com/assets/401167/3535421/f0f36d16-07ff-11e4-8d23-4d535954699b.png)

**Comment by Jumhyn** [comment]
Should be fixed in latest update.

**Comment by tekknolagi** [comment]
@Jumhyn what was wrong & what was fixed?

**Comment by Jumhyn** [comment]
I'm still learning LLVM, but there are no "variables" in the usual sense, because the codegen uses SSA, static single assignment. That means each identifier is assigned exactly once, so something like `%num = sub i32 %num, 1` is invalid. Furthermore, attempting to allocate `num` again with `%num = alloca i32` is wrong for similar reasons. Now, argument identifiers are treated more like normal identifiers, in that they are allocated space on the stack with the initial value of the argument stored into them. In order to get around the fact that the name of the argument is already taken, argument identifiers are denoted like `%num.arg`, which is an invalid identifier in Jum, so there is no risk of conflict.

**Comment by Jumhyn** [comment]
Interestingly, and perhaps faultily, temporary identifiers like `%t7` are also invalid identifiers in Jum, which can only have identifiers that match `[a-zA-Z]`. May push a future update that allows digits in identifiers and has temporary names identify as `%t.7`, for example.

**Comment by Jumhyn** [comment]
Test out arguments and let me know if they appear fixed to you as well!

**Comment by tekknolagi** [comment]
I'm sure if it fixes this bug it should be fine.
